apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test

commonLabels:
  owner: qsw

resources:
- 00_namespace.yaml
- 01_deployment.yaml
- 02_service.yaml
- 03_ingress.yaml

replicas:
- count: 3
  name: deploy-simple-flask-app

images:
- name: flask-app
  newName: polack27/flask-app
  newTag: 0.2.3

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: mydomain.org
  target:
    kind: Ingress
    name: ing-flask-app
